baseURL = "https://wan0514.github.io"
languageCode = "ko"
title = "wanja's blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "wanja"
  defaultTheme = "auto"

[params.homeInfoParams]
  enabled = true
  Title = "wanja's blog"
  Content = "개발과 기록을 담는 공간입니다."
